# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    provision: 'git://github.com/puppetlabs/provision.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
