---
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2018

Rakefile:
  requires:
  use_litmus_tasks: true

# For the moment don't do any rubocop checks.
.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml

spec/default_facts.yml:
  unmanaged: true

# WARN: The puppetlabs/scheduled_task module doesn't support parallel_spec
# PDK Convert will keep adding the default matrix cells instead of replacing them with the below
# After running `pdk convert` you will have to remove the extra cells and keep the ones listed below
# This is raised in https://github.com/puppetlabs/pdk-templates/issues/132
appveyor.yml:
  unmanaged: true

.gitlab-ci.yml:
  delete: true
