---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
".travis.yml":
  deploy_to_forge:
    enabled: false
  simplecov: true
  notifications:
    slack:
      secure: >-
        Wjy6KUrWUFHbMMAeziNZtuvTiK9UHOcGXJmpz3OZ0h16t1CpyL8okFENbG8HkJOXzjL3E27MXpdgAAPACZPHQJkLMFOILDFYTNHSUtgrJfLacY2xudyHEtxmmr7D2QbxsqsUkpwHKZs9S5uHQY3JcB7qu9JCzdxOEF/FGQbNbHoUwnEzVdvYVgTUsYt/yOKkqizdumu5MMqZ8Z+SvHJC/A3BL/I/U/RbmUTldBBSDDzR4RvDLAvlSHnB2wHBWtrnorhC+uLCwjNkO9RQFPwenxVstqRaZ+9rfsk8ceKcAwQ3nXe07QxAZcxvwc1n3+kiUi2fd7gDoaeNp3mdY6ctZIg9tCOdVpGsjL/GzJH8pLv+rMLfo4GmxbZWDCTUxSwhQjBolEUsZy+cpr1o8l+3Ya/gJiEMo3uxNQQXrKiY23Bx7GsYaOiOdfWa0t0r1mZXOn8WD3c5P1V0NHs9NLt7yFfBWXeJE3rgFVf1CHfPYyBFtC1cHIW2j4HMnAc6Sl8+9aPZC390XxNGjsphK+ZH8/SBb6FQKfLyCovvhrMzRzvzhPy2UXIYg/TrOmzNQ2g3cZ9fYyNbM6VVWJGaXNVAxpRf+cu+TGTfptrKota1/HRXCdxOKzuFznaFovkQ+oCF0kr5FSPgerQeAIFA3xtn9JKv1anrpR8U/g55xb/Nr/4=
appveyor.yml:
  use_litmus: true
  spec_type: spec
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  simplecov: true
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
NOTICE:
  copyright_holders:
  - name: Puppet, Inc.
    begin: 2018
Rakefile:
  requires: 
  use_litmus_tasks: true
spec/spec_helper.rb:
  coverage_report: true
