---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true

Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
NOTICE:
  copyright_holders:
  - name: Puppet, Inc.
    begin: 2018
spec/spec_helper.rb:
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  exclude_platforms:
    - Ubuntu-18.04
    - Windows-8.1
  unmanaged: false
.github/workflows/pr_test.yml:
  exclude_platforms:
    - Ubuntu-18.04
    - Windows-8.1
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
