---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  global_env:
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  simplecov: true
  notifications:
    slack:
      secure: >-
        Wjy6KUrWUFHbMMAeziNZtuvTiK9UHOcGXJmpz3OZ0h16t1CpyL8okFENbG8HkJOXzjL3E27MXpdgAAPACZPHQJkLMFOILDFYTNHSUtgrJfLacY2xudyHEtxmmr7D2QbxsqsUkpwHKZs9S5uHQY3JcB7qu9JCzdxOEF/FGQbNbHoUwnEzVdvYVgTUsYt/yOKkqizdumu5MMqZ8Z+SvHJC/A3BL/I/U/RbmUTldBBSDDzR4RvDLAvlSHnB2wHBWtrnorhC+uLCwjNkO9RQFPwenxVstqRaZ+9rfsk8ceKcAwQ3nXe07QxAZcxvwc1n3+kiUi2fd7gDoaeNp3mdY6ctZIg9tCOdVpGsjL/GzJH8pLv+rMLfo4GmxbZWDCTUxSwhQjBolEUsZy+cpr1o8l+3Ya/gJiEMo3uxNQQXrKiY23Bx7GsYaOiOdfWa0t0r1mZXOn8WD3c5P1V0NHs9NLt7yFfBWXeJE3rgFVf1CHfPYyBFtC1cHIW2j4HMnAc6Sl8+9aPZC390XxNGjsphK+ZH8/SBb6FQKfLyCovvhrMzRzvzhPy2UXIYg/TrOmzNQ2g3cZ9fYyNbM6VVWJGaXNVAxpRf+cu+TGTfptrKota1/HRXCdxOKzuFznaFovkQ+oCF0kr5FSPgerQeAIFA3xtn9JKv1anrpR8U/g55xb/Nr/4=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  use_litmus: true
  spec_type: spec
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  simplecov: true
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
NOTICE:
  copyright_holders:
  - name: Puppet, Inc.
    begin: 2018
spec/spec_helper.rb:
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
